/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "Gossip_types.h"
namespace cpp2 {

class GossipConstants {
 public:
  GossipConstants() {}
};

extern const GossipConstants g_Gossip_constants;

} // cpp2